version: '3'
services:
  db:
    container_name: chatting-proto-db
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=chatting-proto
      - TZ=Asia/Seoul
    ports:
      - 3031:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql:/var/lib/mysql

  redis:
    container_name: chatting-proto-redis
    restart: always
    image: redis
    ports:
      - 3032:6379
